import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import BottomBar from '@/components/BottomBar'

const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  // variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Growth Tracker',
  description:
    'App generated by Growth-Track to track physical and spiritual growth of members in HICC-Gbagada',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn('min-h-screen font-sans antialiased', jakarta.className)}
      >
        {children}
        <BottomBar />
      </body>
    </html>
  )
}
